### ISSUE TITLE
Community Workflow fails due to not finding Firebase Key

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [EddieHubCommunity/gh-action-open-source-labels#10]
### Description

Looks like `FIREBASE_KEY` is missing in this repository. I have got the following failure from `community.yml` file.

### Screenshot

<img width="1405" alt="Screen Shot 2021-04-07 at 19 32 36" src="https://user-images.githubusercontent.com/61970868/113894582-3488a580-97d9-11eb-86b2-8bbbaa46f84a.png">

**Comment by eddiejaoude** [comment]
We will be moving away from Firebase soon, with the new API. So this should not be an issue longer term. Thank you for raising 👍
