### ISSUE TITLE
Allow for user labels too

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/gh-action-open-source-labels#14]
```yml
myLabelsFile: mylabels.json
```

and/or

```yml
myLabels: ['label1', 'label2']
```

**Comment by krishdevdb** [comment]
> ```yaml
> myLabelsFile: mylabels.json
> ```
> 
> and/or
> 
> ```yaml
> myLabels: ['label1', 'label2']
> ```

Maybe we can switch this to a nodejs action resulting in ease for us to maintain/contribute and add new features to it?

**Comment by Panquesito7** [comment]
Commented so the issue doesn't get closed (I hope that helps9. 🙂
