### ISSUE TITLE
[DOC] Issue label descriptions and helpful taxonomy of the labels

### ISSUE THREAD

**Issue by tallguyjenks** [EddieHubCommunity/gh-action-open-source-labels#19]
**Description**

Consider adding a table to the README detailing what each tag stands for and/or update the actually label descriptions themselves (can this be done with the GitHub action?) Necessary to provide new users/potential viewers of the repo the information about what the provided labels mean

**Priority**

Non-urgent, but would be a great quality of life improvement

**Screenshots**

Issue description example:

![image](https://user-images.githubusercontent.com/29872822/123385880-e5861d00-d54a-11eb-8210-bcbab67b7406.png)

**Additional Context**    

Join Eddie's discord community [here](http://discord.eddiehub.org)

**Comment by Panquesito7** [comment]
Can someone remove the `no-issue-activity` label, please? Thanks.

**Comment by tallguyjenks** [comment]
🙃
