### ISSUE TITLE
Complete the labels

### ISSUE THREAD

**Issue by krishdevdb** [EddieHubCommunity/gh-action-open-source-labels#20]
**Description**

We don't have all the labels [mentioned](https://opensource.creativecommons.org/contributing-code/repo-labels/)

**Priority**: Medium

**Screenshots**

**Additional Context**    

Join Eddie's discord community [here](http://discord.eddiehub.org)

**Comment by gouravmohanty7070** [comment]
Can I work on it?

**Comment by Sonichigo** [comment]
Hey @gouravmohanty7070 This issue has been resolved!! But u are free to look for the update and work in same!

**Comment by gouravmohanty7070** [comment]
Sure @Sonichigo . Thanks!
