### ISSUE TITLE
Correct the typo

### ISSUE THREAD

**Issue by Sonichigo** [EddieHubCommunity/gh-action-open-source-labels#22]
**Description**

There is small typo in action.yml under owner-name description!
- change onwer to owner!

**Priority**

Priority: Low

**Screenshots**

**Additional Context**    

Join Eddie's discord community [here](http://discord.eddiehub.org)

**Comment by kkhitesh** [comment]
Can I work on the issue?

**Comment by Sonichigo** [comment]
Yeah sure go ahead!

**Comment by kkhitesh** [comment]
Do I edit it directly on github?

**Comment by Sonichigo** [comment]
After forking make the changes then create a pull request!

**Comment by Sonichigo** [comment]
@Vyvy-vi @Panquesito7 ! Please review it!
