### ISSUE TITLE
Make one for Readme Documentation 

### ISSUE THREAD

**Issue by rohank2502** [EddieHubCommunity/gh-action-open-source-labels#3]
Lets make an issue lable for change in documentation in readme so it will be an easy to handle the PR

**Comment by Rahma-AlWadhahi** [comment]
Just to clarify something @rohank2502. You are asking to add a new label in `labels.json` that addresses changes in documentation, right?

**Comment by rohank2502** [comment]
> 
> 
> Just to clarify something @rohank2502. You are asking to add a new label in `labels.json` that addresses changes in documentation, right?

yes

**Comment by eddiejaoude** [comment]
Good idea 👍

**Comment by rohank2502** [comment]
> 
> 
> Good idea 👍

Can I try

**Comment by eddiejaoude** [comment]
Opps I did it already. Sorry @rohank2502

**Comment by rohank2502** [comment]
> 
> 
> Opps I did it already. Sorry @rohank2502

Ya its ok Np
