### ISSUE TITLE
Modifying owner-name and repository-name to be dynamic in README

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [EddieHubCommunity/gh-action-open-source-labels#4]
## Description

It would be cool if we can make the README instructions to use the action to have a dynamic name.

It was a little bit confusing for me to see that it is referring to the same repository that we are in.
I think that changing the **owner name** and the **repository name** to be dynamic will be helpful.

## Screenshot
<img width="852" alt="Screen Shot 2021-04-01 at 19 43 55" src="https://user-images.githubusercontent.com/61970868/113319686-c2b8e380-9322-11eb-8c06-3677f483aa51.png">

## Before Changing

```yaml
         owner-name: 'EddieHubCommunity'
         repository-name: 'gh-action-open-source-labels'
```

## After Changing

```yaml
          owner-name: ${{ github.repository_owner }}
          repository-name: ${{ github.event.repository.name }}
```

**Comment by eddiejaoude** [comment]
Oh nice 👍  great idea 💥
